In [2]:
import stumpy
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

In [8]:

T_A = np.array([1, 0, 3, 9, 2, 1, 1, 15, 3, 3, 4, 5, 6, 7, 132431, 134, 5245, 346, 34634, 14, 2, 10, 7]).astype(np.float64)
m = 3
d = 5

mp_orig = stumpy.stump_dil(T_A=T_A, m=m, d=d)
print(mp_orig)

[[1.1326901826771195e-05 4 -1 4]
 [0.29473436227789124 5 0 8]
 [0.41471759638019673 12 1 12]
 [2.174757693572025 7 0 4]
 [1.1326901826771195e-05 0 0 -1]
 [0.03307097721627579 6 -1 6]
 [0.0009713359357061383 8 0 8]
 [0.04023030898742379 0 0 8]
 [0.00016193831219928835 4 0 9]
 [0.0013073793686425416 11 2 -1]
 [0.02302386069882909 9 0 11]
 [0.0013073793686425416 9 10 12]
 [0.0029862716165679703 11 11 -1]]


In [7]:
# Test same output for same input stump stump_dil
T_A = np.array([1, 2, 3, 0, 3, 9, 2, 1, 2, 3, 1, 15, 3, 14, 2, 10, 7]).astype(np.float64)
m = 3
mp = stumpy.stump(T_A=T_A, m=m)
print(mp)

d=1
mp_dil = stumpy.stump_dil(T_A=T_A, m=m, d=d)
print(mp_dil)

[[0.0 7 -1 7]
 [0.3288114408414133 8 -1 8]
 [0.0 6 0 6]
 [0.3288114408414133 0 0 7]
 [0.09921547503779264 12 1 12]
 [1.3946067503040966 13 2 13]
 [0.0 2 2 11]
 [0.0 0 0 9]
 [0.3288114408414133 1 1 12]
 [0.7997306517513353 3 3 11]
 [0.3589616108906294 12 4 12]
 [0.13015840458292768 6 6 13]
 [0.09921547503779264 4 4 14]
 [0.4461606220875056 11 11 -1]
 [0.9147863787458559 10 10 -1]]


/vol/fob-vol3/mi20/hirschmi/mp_dilation_master/stumpy_master_mp_dilation/stumpy/core.py:67: UserWarning: Excluding `['normalize', 'p']` parameters, function `stump_dil(['T_A', 'm', 'T_B', 'ignore_trivial', 'k', 'd']) and function `aamp(['T_A', 'm', 'T_B', 'ignore_trivial', 'k']) have different arguments/parameters.
  warnings.warn(msg)


[[0.0 7 -1 7]
 [0.3288114408414133 8 -1 8]
 [0.0 6 0 6]
 [0.3288114408414133 0 0 7]
 [0.09921547503779264 12 1 12]
 [1.3946067503040966 13 2 13]
 [0.0 2 2 11]
 [0.0 0 0 9]
 [0.3288114408414133 1 1 12]
 [0.7997306517513353 3 3 11]
 [0.3589616108906294 12 4 12]
 [0.13015840458292768 6 6 13]
 [0.09921547503779264 4 4 14]
 [0.4461606220875056 11 11 -1]
 [0.9147863787458559 10 10 -1]]


### Visualise Discord and Motif Pair ###

In [12]:
mp = mp_orig

def visualise_discord(mp):
    # the global maximum from the matrix profile correspond to the discord
    discord_idx = np.argsort(mp[:, 0])[-1] # startindex of discord with length m

    ## Visualize Discord ##
    fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0})
    plt.suptitle('Discord (Anomaly/Novelty) Discovery', fontsize='30')

    axs[0].plot(ts)
    axs[0].set_ylabel('Sample TS', fontsize='20')
    rect = Rectangle((discord_idx, 0), window_size, np.amax(ts), facecolor='lightgrey')
    axs[0].add_patch(rect)
    axs[1].set_xlabel('Time', fontsize ='20')
    axs[1].set_ylabel('Matrix Profile', fontsize='20')
    axs[1].axvline(x=discord_idx, linestyle="dashed")
    axs[1].plot(mp[:, 0])
    plt.show()
def visualise_motif_pair(mp) -> None:
    # the global minima from the matrix profile correspond to the locations of the two subsequences that make up the motif pair
    motif_idx = np.argsort(mp[:, 0])[0] # startindex of motif with length m
    motif_nearest_neighbor_idx = mp[motif_idx, 1] # startindex of motif with length m

    ## Visualize Motifs ##
    fig, axs = plt.subplots(2, sharex=True, gridspec_kw={'hspace': 0})
    plt.suptitle('Motif (Pattern) Discovery', fontsize='30')

    axs[0].plot(ts)
    axs[0].set_ylabel('Sample TS', fontsize='20')
    rect = Rectangle((motif_idx, 0), window_size, np.amax(ts), facecolor='lightgrey')
    axs[0].add_patch(rect)
    rect = Rectangle((motif_nearest_neighbor_idx, 0), window_size, np.amax(ts), facecolor='lightgrey')
    axs[0].add_patch(rect)
    axs[1].set_xlabel('Time', fontsize ='20')
    axs[1].set_ylabel('Matrix Profile', fontsize='20')
    axs[1].axvline(x=motif_idx, linestyle="dashed")
    axs[1].axvline(x=motif_nearest_neighbor_idx, linestyle="dashed")
    axs[1].plot(mp[:, 0])
    plt.show()

visualise_discord(mp)
visualise_motif_pair(mp)

NameError: name 'mp_orig' is not defined